seed_everything: 42
model:
  class_path: model_cnn.DeBertaModel
data:
  class_path: datamodule.DataModule
  init_args:
    train_path: "trainPlatinum.json"
    val_path: "valPlatinum.json"
    test_path: "testData.json"
    max_len: 500
trainer:
  max_epochs: 100
  devices: 1
  accelerator: gpu
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_f1_micro
        mode: max
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_f1_micro
        save_top_k: 1
        mode: max
        dirpath: "checkpoints/"
        filename: "best-checkpoint"
        save_weights_only: true
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: GutBrainIE
      name: yes_cnn
      log_model: true

